# BERTopic Modeling II
- 원본 데이터(WOS_dat.xls)를 다시 전처리(custom stopwords 추가 및 하이퍼파라미터 조정)한 output_02_cleaned_abstracts.csv로 2차 BERTopic Modeling
- 실행 환경: Colab T4(Python 3)

# [0] Colab 환경 설정

## 0-1. 구글드라이브 마운트

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

## 0-2. 패키지 설치
- 설치 후 런타임 재시작 및 모두 실행

In [2]:
!pip install bertopic
!pip install sentence-transformers
!pip install umap-learn
!pip install hdbscan

Collecting bertopic
  Downloading bertopic-0.17.4-py3-none-any.whl.metadata (24 kB)
Requirement already satisfied: hdbscan>=0.8.29 in /usr/local/lib/python3.12/dist-packages (from bertopic) (0.8.42)
Requirement already satisfied: umap-learn>=0.5.0 in /usr/local/lib/python3.12/dist-packages (from bertopic) (0.5.12)
Requirement already satisfied: numpy>=1.20.0 in /usr/local/lib/python3.12/dist-packages (from bertopic) (2.0.2)
Requirement already satisfied: pandas>=1.1.5 in /usr/local/lib/python3.12/dist-packages (from bertopic) (2.2.2)
Requirement already satisfied: plotly>=4.7.0 in /usr/local/lib/python3.12/dist-packages (from bertopic) (5.24.1)
Requirement already satisfied: scikit-learn>=1.0 in /usr/local/lib/python3.12/dist-packages (from bertopic) (1.6.1)
Requirement already satisfied: sentence-transformers>=0.4.1 in /usr/local/lib/python3.12/dist-packages (from bertopic) (5.4.1)
Requirement already satisfied: tqdm>=4.41.1 in /usr/local/lib/python3.12/dist-packages (from bertopic) (4.67.3)
Requirement already satisfied: llvmlite>0.36.0 in /usr/local/lib/python3.12/dist-packages (from bertopic) (0.43.0)
Requirement already satisfied: scipy>=1.0 in /usr/local/lib/python3.12/dist-packages (from hdbscan>=0.8.29->bertopic) (1.16.3)
Requirement already satisfied: joblib>=1.0 in /usr/local/lib/python3.12/dist-packages (from hdbscan>=0.8.29->bertopic) (1.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.1.5->bertopic) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.1.5->bertopic) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.1.5->bertopic) (2026.1)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly>=4.7.0->bertopic) (9.1.4)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from plotly>=4.7.0->bertopic) (26.1)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.0->bertopic) (3.6.0)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=0.4.1->bertopic) (5.0.0)
Requirement already satisfied: huggingface-hub>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=0.4.1->bertopic) (1.11.0)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=0.4.1->bertopic) (2.10.0+cu128)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=0.4.1->bertopic) (4.15.0)
Requirement already satisfied: numba>=0.51.2 in /usr/local/lib/python3.12/dist-packages (from umap-learn>=0.5.0->bertopic) (0.60.0)
Requirement already satisfied: pynndescent>=0.5 in /usr/local/lib/python3.12/dist-packages (from umap-learn>=0.5.0->bertopic) (0.6.0)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (3.29.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (1.4.3)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (0.28.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (6.0.3)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (0.24.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.1.5->bertopic) (1.17.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (3.1.6)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (1.5.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (0.7.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (2026.4.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (3.13)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (0.16.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (3.0.3)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (8.3.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (0.1.2)
Downloading bertopic-0.17.4-py3-none-any.whl (154 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 154.7/154.7 kB 8.7 MB/s eta 0:00:00
Installing collected packages: bertopic
Successfully installed bertopic-0.17.4
Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.12/dist-packages (5.4.1)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (5.0.0)
Requirement already satisfied: huggingface-hub>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.11.0)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.10.0+cu128)
Requirement already satisfied: numpy>=1.20.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.0.2)
Requirement already satisfied: scikit-learn>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.6.1)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.16.3)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: tqdm>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.67.3)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (3.29.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (1.4.3)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (0.28.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (26.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (6.0.3)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (0.24.2)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.0->sentence-transformers) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.0->sentence-transformers) (3.6.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch>=1.11.0->sentence-transformers) (1.5.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.7.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (2026.4.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (3.13)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (0.16.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.3)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.23.0->sentence-transformers) (8.3.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.23.0->sentence-transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.23.0->sentence-transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.23.0->sentence-transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub>=0.23.0->sentence-transformers) (4.0.0)

## 0-3. 라이브러리 설정
약 1분 소요

In [3]:
import os
import pandas as pd
from bertopic import BERTopic
from sentence_transformers import SentenceTransformer
from sklearn.feature_extraction.text import CountVectorizer
from bertopic.vectorizers import ClassTfidfTransformer
from umap import UMAP
from hdbscan import HDBSCAN

## 0-4. 파일 경로 설정 및 데이터 로드

In [4]:
# 기본 경로
base_path = '/content/drive/MyDrive/Colab Notebooks/GenAI-Finance-TopicModeling/'

# 파일 경로
file_path = os.path.join(
    base_path,
    'outputs',
    'output_02_cleaned_abstracts.csv'
)

# CSV 불러오기
article_df = pd.read_csv(file_path)

# 데이터 확인
print(article_df.shape)

article_df.head()

(602, 4)

,Title,Author,Abstract,Cleaned_Abstract
0,The Odyssey of robots.txt Governance: Measurin...,"Cui, J; Zha, MM; Wang, XF; Liao, XJ",Web content is an essential element for large ...,web content essential element model service su...
1,Evaluation of a Large Language Model on the Am...,"Ramgopal, S; Varma, S; Gorski, JK; Kester, KM;...","BackgroundLarge language models (LLMs), includ...",backgroundlarge model llm including chatgpt ch...
2,HDLGen-ChatGPT Case Study: RISC-V Processor VH...,"Morgan, F; Byrne, JP; Bupathi, A; George, R; E...",This paper presents the open source HDLGen-Cha...,present open source hdlgen chatgpt working tan...
3,Experience with Large Language Model Applicati...,"Yu, L; Alégroth, E; Chatzipetrou, P; Gorschek, T",Large Language Models (LLMs) offer promising c...,model llm offer promising capability informati...
4,Large Language Model Agents for Investment Man...,"Saha, P; Lyu, JR; Saxena, A; Zhao, TJ; Mehta, D",Recent advances in Large Language Models (LLMs...,recent advance model llm triggered new wave in...

# [1] BERTopic Modeling

## 1-1. 문서 리스트 생성

In [5]:
# BERTopic 입력 문서
docs = article_df['Cleaned_Abstract'].tolist()

print(f"문서 개수: {len(docs)}")

문서 개수: 602

## 1-2. 모델 설계

In [6]:
# SentenceTransformer 모델
embedding_model = SentenceTransformer(
    "all-MiniLM-L6-v2"
)

# UMAP 모델: 차원 축소
umap_model = UMAP(
    n_neighbors=10,    # 15 -> 10으로 수정
    n_components=5,
    min_dist=0.0,
    metric='cosine',
    random_state=42
)

# HDBSCAN 모델: 클러스터링
hdbscan_model = HDBSCAN(
    min_cluster_size=8,      # 15 -> 8로 수정
    metric='euclidean',
    cluster_selection_method='eom',
    prediction_data=True
)

# CountVectorizer 모델: BoW 벡터화
vectorizer_model = CountVectorizer(
    stop_words='english',
    ngram_range=(1, 2),      # 5 -> 3으로 수정
)

# c-tf-idf 모델: 토픽별 중요 단어 계산
ctfidf_model = ClassTfidfTransformer()

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

## 1-3. BERTopic 모델 생성

In [7]:
topic_model = BERTopic(
    embedding_model=embedding_model,
    umap_model=umap_model,
    hdbscan_model=hdbscan_model,
    vectorizer_model=vectorizer_model,
    ctfidf_model=ctfidf_model,
    nr_topics="auto",    # 8 -> auto 로 수정 (모델이 적절하다고 판단하는 토픽 개수 자동으로 결정하도록)
    calculate_probabilities=True,
    verbose=True
)

## 1-4. 모델 학습

In [8]:
topics, probs = topic_model.fit_transform(docs)

2026-05-21 03:53:58,355 - BERTopic - Embedding - Transforming documents to embeddings.

Batches:   0%|          | 0/19 [00:00<?, ?it/s]

2026-05-21 03:54:00,349 - BERTopic - Embedding - Completed ✓
2026-05-21 03:54:00,350 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2026-05-21 03:54:10,844 - BERTopic - Dimensionality - Completed ✓
2026-05-21 03:54:10,845 - BERTopic - Cluster - Start clustering the reduced embeddings
2026-05-21 03:54:10,890 - BERTopic - Cluster - Completed ✓
2026-05-21 03:54:10,891 - BERTopic - Representation - Extracting topics using c-TF-IDF for topic reduction.
2026-05-21 03:54:11,157 - BERTopic - Representation - Completed ✓
2026-05-21 03:54:11,158 - BERTopic - Topic reduction - Reducing number of topics
2026-05-21 03:54:11,167 - BERTopic - Representation - Fine-tuning topics using representation models.
2026-05-21 03:54:11,430 - BERTopic - Representation - Completed ✓
2026-05-21 03:54:11,432 - BERTopic - Topic reduction - Reduced number of topics from 15 to 15

## 1-5. 결과 확인

### 토픽 결과 확인

In [9]:
print("[토픽 정보]")
topic_info = topic_model.get_topic_info()
topic_info

[토픽 정보]

,Topic,Count,Name,Representation,Representative_Docs
0,-1,160,-1_model_data_llm_domain,"[model, data, llm, domain, finance, financial,...",[traditional model nlp require considerable am...
1,0,110,0_generative_financial_data_technology,"[generative, financial, data, technology, fina...",[discusses transformative impact emerging digi...
2,1,92,1_question_chatgpt_medical_performance,"[question, chatgpt, medical, performance, accu...",[background artificial intelligence potential ...
3,2,41,2_sentiment_market_financial_model,"[sentiment, market, financial, model, trading,...",[financial sentiment analysis fsa aim infer se...
4,3,40,3_privacy_security_data_attack,"[privacy, security, data, attack, vulnerabilit...",[model llm widely adopted different domain inc...
5,4,22,4_contract_blockchain_defi_smart contract,"[contract, blockchain, defi, smart contract, s...",[rampant scam plague decentralized finance def...
6,5,20,5_retrieval_rag_domain_generation,"[retrieval, rag, domain, generation, augmented...",[rapid advancement intelligent retrieval techn...
7,6,19,6_llm_test_api_domain,"[llm, test, api, domain, tool, model, apis, pr...",[fintech software crucial safety timely market...
8,7,19,7_memory_pim_bank_dram,"[memory, pim, bank, dram, inference, processin...",[deploying model llm edge device pose signific...
9,8,15,8_extraction_narrative_entity_model,"[extraction, narrative, entity, model, text, d...",[story component namely event participant rela...
10,9,15,9_financial_task_llm_model,"[financial, task, llm, model, instruction, fin...",[despite spanish pivotal role global finance i...
11,10,14,10_student_question_education_chatgpt,"[student, question, education, chatgpt, higher...",[generative artificial intelligence aigcp cont...
12,11,14,11_video_visual_frame_multimodal,"[video, visual, frame, multimodal, model, memo...",[current landscape leveraging model llm experi...
13,12,13,12_bias_fairness_llm_model,"[bias, fairness, llm, model, uncertainty, metr...",[model llm continue advance utilized across so...
14,13,8,13_hallucination_generation_legal_llm,"[hallucination, generation, legal, llm, halluc...",[retrieval augmented generation rag framework ...

### 토픽 키워드 확인

In [10]:
for topic_num in topic_info['Topic']:
    if topic_num != -1:
        print(f"\n[Topic {topic_num}]")
        print(topic_model.get_topic(topic_num))

[Topic 0]
[('generative', np.float64(0.01698633485758705)), ('financial', np.float64(0.016769941916633356)), ('data', np.float64(0.015091077123159831)), ('technology', np.float64(0.01491022038090518)), ('finance', np.float64(0.013982399746447308)), ('model', np.float64(0.013843866830528849)), ('intelligence', np.float64(0.01205700067170034)), ('industry', np.float64(0.01190963013421434)), ('human', np.float64(0.010724637533315404)), ('artificial', np.float64(0.010596210441713683))]

[Topic 1]
[('question', np.float64(0.04467395921665182)), ('chatgpt', np.float64(0.033289151908881535)), ('medical', np.float64(0.02274977992941602)), ('performance', np.float64(0.021358652158875575)), ('accuracy', np.float64(0.01895244360392652)), ('clinical', np.float64(0.017022465518402172)), ('examination', np.float64(0.01650659335758051)), ('model', np.float64(0.01572162453355399)), ('llm', np.float64(0.014994310112651461)), ('answer', np.float64(0.014393538582439691))]

[Topic 2]
[('sentiment', np.float64(0.03568574781802621)), ('market', np.float64(0.029634635093497688)), ('financial', np.float64(0.02651687522326158)), ('model', np.float64(0.02452042147193338)), ('trading', np.float64(0.01839638815676305)), ('analysis', np.float64(0.01755654032665299)), ('data', np.float64(0.016918420587494324)), ('llm', np.float64(0.016357739273640086)), ('news', np.float64(0.015263164498006436)), ('sentiment analysis', np.float64(0.014995699795990657))]

[Topic 3]
[('privacy', np.float64(0.0258647590357706)), ('security', np.float64(0.021989408433576885)), ('data', np.float64(0.021884364632738563)), ('attack', np.float64(0.020020625346467275)), ('vulnerability', np.float64(0.019312011630193367)), ('model', np.float64(0.01710844790865623)), ('threat', np.float64(0.01474787459950843)), ('agent', np.float64(0.014632086303247435)), ('usepackage', np.float64(0.014303708748504729)), ('detection', np.float64(0.013117165895439363))]

[Topic 4]
[('contract', np.float64(0.04924845769141761)), ('blockchain', np.float64(0.04844065558615001)), ('defi', np.float64(0.04470777846075923)), ('smart contract', np.float64(0.042199115216973414)), ('smart', np.float64(0.04205154638161632)), ('vulnerability', np.float64(0.03363300476810791)), ('decentralized', np.float64(0.02467378085938948)), ('transaction', np.float64(0.01720742112083894)), ('detection', np.float64(0.01712412868614405)), ('security', np.float64(0.016916399405232235))]

[Topic 5]
[('retrieval', np.float64(0.05478781532463976)), ('rag', np.float64(0.041479261281714676)), ('domain', np.float64(0.029544192706424048)), ('generation', np.float64(0.021222649460706497)), ('augmented', np.float64(0.020251201496819863)), ('document', np.float64(0.019928994026732882)), ('retrieval augmented', np.float64(0.018919216041212848)), ('benchmark', np.float64(0.018718427838629485)), ('domain specific', np.float64(0.018352427382544147)), ('augmented generation', np.float64(0.01808157986724945))]

[Topic 6]
[('llm', np.float64(0.025309051521536625)), ('test', np.float64(0.023749370402789786)), ('api', np.float64(0.022883919677798088)), ('domain', np.float64(0.016569999479779107)), ('tool', np.float64(0.016363830517330438)), ('model', np.float64(0.016088884132974903)), ('apis', np.float64(0.015664860195057178)), ('prompt', np.float64(0.015167735922927483)), ('software', np.float64(0.014246481997544786)), ('case', np.float64(0.013376544228981626))]

[Topic 7]
[('memory', np.float64(0.06145701906320331)), ('pim', np.float64(0.0544601529969374)), ('bank', np.float64(0.030927729206382395)), ('dram', np.float64(0.02499376066303467)), ('inference', np.float64(0.02432474265472382)), ('processing', np.float64(0.02143150065294443)), ('gemv', np.float64(0.016673650377064926)), ('bandwidth', np.float64(0.016673650377064926)), ('computation', np.float64(0.01666250710868978)), ('model', np.float64(0.016287627345580653))]

[Topic 8]
[('extraction', np.float64(0.04155837172297576)), ('narrative', np.float64(0.030595115905662554)), ('entity', np.float64(0.029551825050587247)), ('model', np.float64(0.02924759635704514)), ('text', np.float64(0.023753101951220903)), ('data', np.float64(0.022485942728422224)), ('document', np.float64(0.02235287700299195)), ('information', np.float64(0.022062075181469982)), ('domain', np.float64(0.021328358235278295)), ('phrase', np.float64(0.020899283400026263))]

[Topic 9]
[('financial', np.float64(0.07651746078118266)), ('task', np.float64(0.040678120116542864)), ('llm', np.float64(0.03892843848400575)), ('model', np.float64(0.026791283359176778)), ('instruction', np.float64(0.025191048709913153)), ('financial task', np.float64(0.025172049461334903)), ('datasets', np.float64(0.024748424618785094)), ('domain', np.float64(0.024123214067112615)), ('benchmark', np.float64(0.022943243547229965)), ('data', np.float64(0.0215968815967989))]

[Topic 10]
[('student', np.float64(0.05548272667235112)), ('question', np.float64(0.033011526311752325)), ('education', np.float64(0.028292233548464215)), ('chatgpt', np.float64(0.02614349976457861)), ('higher education', np.float64(0.02535414521837048)), ('higher', np.float64(0.021323866569801266)), ('exercise', np.float64(0.019166576757294773)), ('bank', np.float64(0.01852660018710454)), ('educational', np.float64(0.018036999095571608)), ('generative', np.float64(0.01780373716626178))]

[Topic 11]
[('video', np.float64(0.04537127452494265)), ('visual', np.float64(0.030852466676961)), ('frame', np.float64(0.030689254200771413)), ('multimodal', np.float64(0.028138304641607506)), ('model', np.float64(0.027072889726484875)), ('memory', np.float64(0.026587593003294663)), ('image', np.float64(0.021290500050511287)), ('object', np.float64(0.020459502800514277)), ('long', np.float64(0.019976826573669185)), ('memory bank', np.float64(0.019633935639043424))]

[Topic 12]
[('bias', np.float64(0.057719795731485696)), ('fairness', np.float64(0.0387016454351415)), ('llm', np.float64(0.033300016591449384)), ('model', np.float64(0.026316973295505343)), ('uncertainty', np.float64(0.023816804818771343)), ('metric', np.float64(0.01852001680136209)), ('risk', np.float64(0.01664242994505681)), ('evaluation', np.float64(0.01637106753060854)), ('data', np.float64(0.016123044833587428)), ('including', np.float64(0.015168955392292134))]

[Topic 13]
[('hallucination', np.float64(0.0795457105062184)), ('generation', np.float64(0.03924670702797075)), ('legal', np.float64(0.028677106698114126)), ('llm', np.float64(0.021723479289613493)), ('hallucinated', np.float64(0.021676155471696507)), ('model', np.float64(0.021498379321085396)), ('domain', np.float64(0.020694116933693867)), ('inconsistency', np.float64(0.01990632663394544)), ('definition', np.float64(0.01990632663394544)), ('error', np.float64(0.017519646499663505))]

## 1-6. 결과 저장

In [17]:
topic_info.to_csv(
    os.path.join(
        base_path,
        'outputs',
        'output_03_topic_info.csv'
    ),
    index=False,
    encoding='utf-8-sig'
)

# [2] 시각화

## 2-1. Intertopic Distance Map

In [12]:
topic_model.visualize_topics()

## 2-2. Topic Word Scores

In [13]:
topic_model.visualize_barchart(
    top_n_topics=len(topic_info)-1
)

## 2-3. Topic Similarity Heatmap

In [14]:
topic_model.visualize_heatmap()